version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    networks:
     app_net:
       ipv4_address: 172.16.238.10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grader
    ports:
    - "5435:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: work.interin2@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: grader2
    ports:
      - "5050:80"
    networks:
     app_net:
       ipv4_address: 172.16.238.11
  memcached:
    container_name: memcached_container
    image: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
     app_net:
       ipv4_address: 172.16.238.12
  nats-streaming:
    container_name: nats-streaming_container
    image: nats-streaming
    networks:
     app_net:
       ipv4_address: 172.16.238.13
    restart: always
    ports:
      - "4222:4222"
      
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24