web_url: http://0.0.0.0:8080
broker_url: 172.16.238.13:4222
db_driver: postgres
db_connection: host=172.16.238.10 port=5432 user=root password=root dbname=grader sslmode=disable
memcached_url: 172.16.238.12:11211
zip_arch_path: /media/artyom/H/solutions/temp-zip
tests_path: /media/artyom/H/solutions/tests